### ISSUE TITLE
Makefile of GraphicsMagick of ADSupport treats "implicit-function-declaration" as error

### ISSUE THREAD

**Issue by devilkingsatan666** [areaDetector/areaDetector#78]
Dear all, 

I am sorry to take your time/space for this novice question. After downloading all the synApps components with the installer script from the [repo](https://github.com/EPICS-synApps/support) and confirming that all the paths were well replaced, I got an error during compilation for GraphicsMagick saying that the Warning: "implicit-function-declaration" was treated as an error instead. The compiler is gcc (Debian 8.3.0-6) 8.3.0 on Debian 10, and the following is a snippet of the error.

> make[7]: Entering directory '/opt/epics/R70.5/synApps/support/areaDetector-R3-10/ADSupport/supportApp/GraphicsMagickSrc/webp/src/O.linux-x86_64'
/usr/bin/gcc  -D_GNU_SOURCE -D_DEFAULT_SOURCE           -D_X86_64_  -DUNIX  -Dlinux      -O3 -g   -Wall -Werror-implicit-function-declaration     -D_WEBPLIB_  -mtune=generic      -m64 -fPIC -I. -I../O.Common -I. -I. -I.. -I../../../../../supportApp/GraphicsMagickSrc/webp/src/dec -I../../../../../supportApp/GraphicsMagickSrc/webp/src/demux -I../../../../../supportApp/GraphicsMagickSrc/webp/src/dsp -I../../../../../supportApp/GraphicsMagickSrc/webp/src/enc -I../../../../../supportApp/GraphicsMagickSrc/webp/src/mux -I../../../../../supportApp/GraphicsMagickSrc/webp/src/utils -I../../../../../include/compiler/gcc -I../../../../../include/os/Linux -I../../../../../include      -I/opt/epics/R70.5/synApps/support/asyn-R4-41/include     -I/opt/epics/R70.5/synApps/support/areaDetector-R3-10/ADSupport/include/os/Linux -I/opt/epics/R70.5/synApps/support/areaDetector-R3-10/ADSupport/include    -I/opt/epics/R70.5/base/include/compiler/gcc -I/opt/epics/R70.5/base/include/os/Linux -I/opt/epics/R70.5/base/include     -I../../../../../supportApp/GraphicsMagickSrc    -c ../../../../../supportApp/GraphicsMagickSrc/webp/src/dec/alphadec.c
../../../../../supportApp/GraphicsMagickSrc/webp/src/dec/alphadec.c: In function ‘ALPHDelete’:
../../../../../supportApp/GraphicsMagickSrc/webp/src/dec/alphadec.c:35:5: error: implicit declaration of function ‘VP8LDelete’; did you mean ‘VP8Delete’? [-Werror=implicit-function-declaration]
     VP8LDelete(dec->vp8l_dec_);
     ^~~~~~~~~~
     VP8Delete
../../../../../supportApp/GraphicsMagickSrc/webp/src/dec/alphadec.c: In function ‘ALPHInit’:
../../../../../supportApp/GraphicsMagickSrc/webp/src/dec/alphadec.c:100:10: error: implicit declaration of function ‘VP8LDecodeAlphaHeader’ [-Werror=implicit-function-declaration]
     ok = VP8LDecodeAlphaHeader(dec, alpha_data, alpha_data_size);
          ^~~~~~~~~~~~~~~~~~~~~
../../../../../supportApp/GraphicsMagickSrc/webp/src/dec/alphadec.c: In function ‘ALPHDecode’:
../../../../../supportApp/GraphicsMagickSrc/webp/src/dec/alphadec.c:139:10: error: implicit declaration of function ‘VP8LDecodeAlphaImageStream’; did you mean ‘VP8LEncodeStream’? [-Werror=implicit-function-declaration]
     if (!VP8LDecodeAlphaImageStream(alph_dec, row + num_rows)) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
          VP8LEncodeStream
cc1: some warnings being treated as errors
make[7]: *** [/opt/epics/R70.5/base/configure/RULES_BUILD:255: alphadec.o] Error 1
make[7]: Leaving directory '/opt/epics/R70.5/synApps/support/areaDetector-R3-10/ADSupport/supportApp/GraphicsMagickSrc/webp/src/O.linux-x86_64'

One way I can come up with to bypass it is to remove the flag "Werror-implicit-function-declaration" from its Makefile. Though, It might be a better solution that I re-declare all the functions to fix it. Are there any other safe ways to fix this? Thank you for the replies in advance.

**Comment by devilkingsatan666** [comment]
After executing make -i clean uninstall, it continued to finish compiling all the ADsupport libs.

**Comment by MarkRivers** [comment]
The problem is that you modified the assemble_synApps.sh script to use base 7.0.5 rather than 3.15.6.  7.0.5 changed the compiler settings to make implicit function declarations an error rather than a warning.

However, the errors you are getting have already been fixed so ADSupport builds with base 7.0.5.  You just need to use ADSupport R1-9-1 rather than R1-9.

**Comment by devilkingsatan666** [comment]
Thank you so much for your help. It works great.
